# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1356, 831)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.button_refrush = QtWidgets.QPushButton(self.widget_6)
        self.button_refrush.setObjectName("button_refrush")
        self.gridLayout_5.addWidget(self.button_refrush, 1, 0, 1, 1)
        self.tableView_process = QtWidgets.QTableView(self.widget_6)
        self.tableView_process.setObjectName("tableView_process")
        self.gridLayout_5.addWidget(self.tableView_process, 2, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_6)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.widget_6, 1, 3, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.listView_local = QtWidgets.QListView(self.widget_2)
        self.listView_local.setObjectName("listView_local")
        self.gridLayout_3.addWidget(self.listView_local, 3, 0, 1, 3)
        self.button_local_up = QtWidgets.QPushButton(self.widget_2)
        self.button_local_up.setMaximumSize(QtCore.QSize(60, 16777215))
        self.button_local_up.setStyleSheet("")
        self.button_local_up.setObjectName("button_local_up")
        self.gridLayout_3.addWidget(self.button_local_up, 2, 0, 1, 1)
        self.local_dir = QtWidgets.QLineEdit(self.widget_2)
        self.local_dir.setObjectName("local_dir")
        self.gridLayout_3.addWidget(self.local_dir, 1, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.button_right = QtWidgets.QPushButton(self.widget_3)
        self.button_right.setObjectName("button_right")
        self.verticalLayout.addWidget(self.button_right)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.button_left = QtWidgets.QPushButton(self.widget_3)
        self.button_left.setObjectName("button_left")
        self.verticalLayout.addWidget(self.button_left)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.gridLayout.addWidget(self.widget_3, 1, 1, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listView_server = QtWidgets.QListView(self.widget_4)
        self.listView_server.setObjectName("listView_server")
        self.gridLayout_2.addWidget(self.listView_server, 3, 0, 1, 4)
        self.server_dir = QtWidgets.QLineEdit(self.widget_4)
        self.server_dir.setReadOnly(True)
        self.server_dir.setObjectName("server_dir")
        self.gridLayout_2.addWidget(self.server_dir, 1, 0, 1, 4)
        self.button_changeC = QtWidgets.QPushButton(self.widget_4)
        self.button_changeC.setObjectName("button_changeC")
        self.gridLayout_2.addWidget(self.button_changeC, 2, 2, 1, 1)
        self.button_server_up = QtWidgets.QPushButton(self.widget_4)
        self.button_server_up.setMaximumSize(QtCore.QSize(60, 16777215))
        self.button_server_up.setObjectName("button_server_up")
        self.gridLayout_2.addWidget(self.button_server_up, 2, 0, 1, 1)
        self.button_changeD = QtWidgets.QPushButton(self.widget_4)
        self.button_changeD.setObjectName("button_changeD")
        self.gridLayout_2.addWidget(self.button_changeD, 2, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 4)
        self.gridLayout.addWidget(self.widget_4, 1, 2, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_address = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_address.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.horizontalLayout.addWidget(self.lineEdit_address)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_port = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_port.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.horizontalLayout.addWidget(self.lineEdit_port)
        self.button_connect = QtWidgets.QPushButton(self.widget)
        self.button_connect.setObjectName("button_connect")
        self.horizontalLayout.addWidget(self.button_connect)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 3)
        self.widget_7 = QtWidgets.QWidget(self.centralwidget)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.button_open_process = QtWidgets.QPushButton(self.widget_7)
        self.button_open_process.setObjectName("button_open_process")
        self.gridLayout_6.addWidget(self.button_open_process, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_7)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 1, 0, 1, 1)
        self.lineEdit_open_process = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_open_process.setObjectName("lineEdit_open_process")
        self.gridLayout_6.addWidget(self.lineEdit_open_process, 2, 0, 1, 3)
        self.gridLayout.addWidget(self.widget_7, 2, 2, 1, 2)
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.log_list = QtWidgets.QTextBrowser(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_list.sizePolicy().hasHeightForWidth())
        self.log_list.setSizePolicy(sizePolicy)
        self.log_list.setMinimumSize(QtCore.QSize(0, 0))
        self.log_list.setObjectName("log_list")
        self.gridLayout_4.addWidget(self.log_list, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_5)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_5, 2, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "远程文件传输"))
        self.button_refrush.setText(_translate("MainWindow", "刷新"))
        self.label_5.setText(_translate("MainWindow", "进程列表"))
        self.button_local_up.setText(_translate("MainWindow", "上一级"))
        self.label.setText(_translate("MainWindow", "本地(回车跳转）"))
        self.button_right.setText(_translate("MainWindow", "→"))
        self.button_left.setText(_translate("MainWindow", "←"))
        self.button_changeC.setText(_translate("MainWindow", "切换C盘"))
        self.button_server_up.setText(_translate("MainWindow", "上一级"))
        self.button_changeD.setText(_translate("MainWindow", "切换D盘"))
        self.label_2.setText(_translate("MainWindow", "远程"))
        self.label_3.setText(_translate("MainWindow", "IP"))
        self.lineEdit_address.setText(_translate("MainWindow", "localhost"))
        self.label_4.setText(_translate("MainWindow", "端口"))
        self.lineEdit_port.setText(_translate("MainWindow", "2121"))
        self.button_connect.setText(_translate("MainWindow", "连接"))
        self.button_open_process.setText(_translate("MainWindow", "打开程序"))
        self.label_6.setText(_translate("MainWindow", "（输入文件路径）"))
        self.label_7.setText(_translate("MainWindow", "消息"))
